import express from 'express';
import { TenantController } from '../controllers/tenanrController';
import { TenantService } from '../services/tenantService';
import { AppDataSource } from '../config/data-source';
import { Tenant } from '../entities/tenents';
import { logger } from '../config/logger';
const router = express.Router();
const tenantRepositary = AppDataSource.getRepository(Tenant);
const tenantService = new TenantService(tenantRepositary);
const tenantController = new TenantController(tenantService, logger);
router.post('/', (req, res, next) => tenantController.create(req, res, next));
export default router;
